apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    quay-component: clair-app
  name: clair-app
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: clair-app
  template:
    metadata:
      labels:
        quay-component: clair-app
    spec:
      serviceAccountName: clair-app
      containers:
        - image: quay.io/projectquay/clair@sha256:5fec3cf459159eabe2e4e1089687e25f638183a7e9bed1ecea8724e0597f8a14
          imagePullPolicy: IfNotPresent
          name: clair-app
          env:
            - name: CLAIR_CONF
              value: /clair/config.yaml
            - name: CLAIR_MODE
              value: combo
          ports:
            - containerPort: 8080
              name: clair-http
              protocol: TCP
            - containerPort: 8089
              name: clair-intro
              protocol: TCP
          volumeMounts:
            - mountPath: /clair/
              name: config
            - mountPath: /var/run/certs
              name: certs
          startupProbe:
            tcpSocket:
              port: clair-intro
            periodSeconds: 10
            failureThreshold: 300
          readinessProbe:
            tcpSocket:
              port: 8080
          livelinessProbe:
            httpGet:
              port: clair-intro
              path: /healthz
          resources:
            requests:
              cpu: 2000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 16Gi
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: clair-config-secret
        - name: certs
          secret:
            secretName: quay-config-tls
            # Mount just the public certificate because we are using storage proxying.
            items:
              - key: ssl.cert
                path: quay-ssl.cert
