apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app-upgrade
spec:
  template:
    metadata:
      labels:
        quay-component: quay-app-upgrade
    spec:
      # Init conatainer needed to wait for Clair to initialize (can take minutes) before attempting to validate config.
      initContainers:
        - name: quay-app-upgrade-init
          image: quay.io/projectquay/quay@sha256:a544ee36a20cb24d02a5f7b70daef776b169e3b2cdfc8f5dcf605475067ac8b0
          command:
            - /bin/sh
            - -c
            - curl $CLAIR_SERVICE_HOST
          env:
            - name: CLAIR_SERVICE_HOST
              value: $(CLAIR_SERVICE_HOST)
