apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-mirror
  labels:
    quay-component: quay-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: quay-mirror
  template:
    metadata:
      labels:
        quay-component: quay-mirror
    spec:
      volumes:
        - name: configvolume
          secret:
            secretName: quay-config-secret
        - name: extra-ca-certs
          projected:
            sources:
              - configMap:
                  name: cluster-service-ca
              - secret:
                  name: quay-config-secret
                  items:
                    - key: ssl.cert
                      path: quay-ssl.cert
      # FIXME(alecmerdler): May need an `initContainer` which blocks until Quay app is running...
      containers:
        - name: quay-mirror
          image: quay.io/projectquay/quay@sha256:6fe0cfe3ecb544f273d775d16f03e6dff7313775af982dbbd546bf976e3c97e3
          command: ["/quay-registry/quay-entrypoint.sh"]
          args: ["repomirror-nomigrate"]
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME(alecmerdler): Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "true"
            - name: ENSURE_NO_MIGRATION
              value: "true"
          # TODO: Determine if we need to set resource requirements
          volumeMounts:
            - name: configvolume
              readOnly: false
              mountPath: /conf/stack
            - name: extra-ca-certs
              readOnly: true
              mountPath: /conf/stack/extra_ca_certs
