apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-mirror
  labels:
    quay-component: quay-mirror
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      quay-component: quay-mirror
  template:
    metadata:
      labels:
        quay-component: quay-mirror
    spec:
      volumes:
        - name: configvolume
          secret:
            secretName: quay-config-secret
        - name: extra-ca-certs
          projected:
            sources:
              - configMap:
                  name: cluster-service-ca
              - secret:
                  name: quay-config-secret
                  items:
                    - key: ssl.cert
                      path: quay-ssl.cert
      initContainers:
        - name: quay-mirror-init
          image: quay.io/projectquay/quay@sha256:a544ee36a20cb24d02a5f7b70daef776b169e3b2cdfc8f5dcf605475067ac8b0
          command:
            - /bin/sh
            - -c
            - curl $QUAY_APP_SERVICE_HOST
          env:
            - name: QUAY_APP_SERVICE_HOST
              value: $(QUAY_APP_SERVICE_HOST)
      containers:
        - name: quay-mirror
          image: quay.io/projectquay/quay@sha256:a544ee36a20cb24d02a5f7b70daef776b169e3b2cdfc8f5dcf605475067ac8b0
          command: ["/quay-registry/quay-entrypoint.sh"]
          args: ["repomirror-nomigrate"]
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME(alecmerdler): Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "false"
            - name: ENSURE_NO_MIGRATION
              value: "true"
          # TODO: Determine if we need to set resource requirements
          volumeMounts:
            - name: configvolume
              readOnly: false
              mountPath: /conf/stack
            - name: extra-ca-certs
              readOnly: true
              mountPath: /conf/stack/extra_ca_certs
