apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-database
  labels:
    quay-component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: postgres
  template:
    metadata:
      labels:
        quay-component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: quay-database
      # FIXME(alecmerdler): Need to set `fsGroup: 0` for `centos/postgresql-10-centos7` but not `rhel8/postgresql-10`
      securityContext:
        fsGroup: 0
      containers:
        - name: postgres
          image: centos/postgresql-10-centos7@sha256:de1560cb35e5ec643e7b3a772ebaac8e3a7a2a8e8271d9e91ff023539b4dfb33
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          # TODO(alecmerdler): Readiness/liveliness probes which execute `psql` command to check if database is created.
          env:
            - name: POSTGRESQL_USER
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRESQL_DATABASE
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
