# Overlay variant for upgrading to current Project Quay release.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../tmp
patchesStrategicMerge:
  # Scale the app deployment to 0 pods in order to run all migrations present in the new container image using the "upgrade" deployment.
  - ./quay.deployment.patch.yaml
  - ./upgrade.deployment.patch.yaml
