apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
spec:
  sourceType: grpc
  image: quay.io/projectquay/quay-operator-catalog@sha256:598dc75adf6da2c0fa82d34ecda88bf71f254518fc87d0d9374027a57c911ead
