apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: quay-operator
spec:
  sourceType: grpc
  image: quay.io/projectquay/quay-operator-catalog@sha256:66f23a75be0db3df3addba246ee8b179a5d3e495cdf55a841f605f97649d6b56
