apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: old
spec:
  quay: 
    imagePullSecretName: redhat-pull-secret
    database: 
      volumeSize: 10Gi
      credentialsSecretName: old-quay-database
    externalAccess:
      tls:
        secretName: old-quay-tls
        termination: passthrough
    registryBackends:
      - name: <driver>
        rhocs:
          hostname: <hostname>
          port: 443
          secure: true
          accessKey: <accessKey>
          secretKey: <secretKey>
          bucketName: <bucketName>
    configFiles:
      - secretName: quay-extra-certs
        type: extraCaCert
  # Ignore Clair v2, TNG only deploys Clair v4
  clair: {}
  # Ignore Redis, the data it contains should be treated as ephemeral.
  redis: {}
