apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: old
spec:
  quay: 
    imagePullSecretName: redhat-pull-secret
    database: 
      volumeSize: 10Gi
      credentialsSecretName: old-quay-database
    externalAccess:
      type: LoadBalancer
      hostname: projquay-1345.skynet-dev.com
    registryBackends:
      - name: default
        rhocs:
          hostname: s3.openshift-storage.svc
          port: 443
          secure: true
          accessKey: uxf9MtIRvsGLxCmbUcXR
          secretKey: j2+KBW+rOl4efOdtzLQXGMMC0u8xMEgPxyAAqBjs
          bucketName: projquay-1345-7f6ce2ff-1efb-4e67-9be5-3128967ef0f9
    configFiles:
      - secretName: quay-extra-certs
        type: extraCaCert
  # Ignore Clair v2, TNG only deploys Clair v4
  clair: {}
  # Ignore Redis, the data it contains should be treated as ephemeral.
  redis: {}
