apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-config-editor
  labels:
    quay-component: quay-config-editor
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-component: quay-config-editor
  template:
    metadata:
      labels:
        quay-component: quay-config-editor
    spec:
      volumes:
        - name: config-bundle
          secret:
            secretName: quay-config-secret
        - name: extra-ca-certs
          configMap:
            name: cluster-service-ca
      containers:
        - name: quay-config-editor
          image: quay.io/projectquay/quay@sha256:8687bb4d2279f1747725f15318bb86a20b8ee131e2ca49d49f5dbe2d03d14cd2
          ports:
            - containerPort: 8080
              protocol: TCP
          args: ["config", "$(QUAY_PASSWORD)", "$(QUAY_OPERATOR_ENDPOINT)"]
          env:
            - name: QUAY_CONFIG_PATH
              value: /conf/stack
            - name: DEBUGLOG
              value: "true"
            - name: QUAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quay-config-editor-credentials
                  key: password
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: QUAY_OPERATOR_ENDPOINT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['quay-operator-service-endpoint']
            - name: QUAY_CONFIG_READ_ONLY_FIELD_GROUPS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['quay-managed-fieldgroups']
          volumeMounts:
            - name: config-bundle
              mountPath: /conf/stack
            - name: extra-ca-certs
              mountPath: /conf/stack/extra_ca_certs
