apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app-upgrade
  labels:
    quay-component: quay-app-upgrade
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      quay-component: quay-app-upgrade
  template:
    metadata:
      labels:
        quay-component: quay-app-upgrade
    spec:
      serviceAccountName: quay-app
      volumes:
        - name: config
          projected:
            sources:
            - secret:
                name: quay-config-secret
            - secret:
                name: quay-config-tls
        - name: extra-ca-certs
          configMap:
            name: cluster-service-ca
      containers:
        - name: quay-app-upgrade
          image: quay.io/projectquay/quay@sha256:46334210eeb21aa6205215d1c4dbc40ea3381887c21a05d0bc47203c8f938987
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME: Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "false"
            - name: WORKER_COUNT_WEB
              value: "4"
            - name: WORKER_COUNT_SECSCAN
              value: "2"
            - name: WORKER_COUNT_REGISTRY
              value: "8"
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 2000m
              memory: 8Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          startupProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
            timeoutSeconds: 20
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
          livelinessProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
          volumeMounts:
            - name: config
              readOnly: false
              mountPath: /conf/stack
            - name: extra-ca-certs
              readOnly: true
              mountPath: /conf/stack/extra_ca_certs
